volumes:
  spotdb-postgres-data:
    external: true


services:
  fastapi:
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      DATABASE_URL: postgresql://spotdb:password@postgres/spotdb
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  postgres:
    image: postgres:14.5-bullseye
    volumes:
      - spotdb-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: spotdb
      POSTGRES_DB: spotdb
    ports:
      - 15432:5432
